# Generated by Django 5.2.1 on 2025-05-27 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('country_code', models.CharField(default='+971', max_length=5, validators=[django.core.validators.RegexValidator(message="Country code must be in format '+XXX' (e.g., +971)", regex='^\\+\\d{1,4}$')])),
                ('company', models.CharField(blank=True, max_length=100)),
                ('profession', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Registrations',
                'db_table': 'api_registration',
            },
        ),
    ]
