# Generated by Django 5.2.1 on 2025-05-27 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='country_code',
            field=models.CharField(default='+971', max_length=5, validators=[django.core.validators.RegexValidator(message="Country code must be in format '+XXX' (e.g., +971)", regex='^\\+\\d{1,4}$')]),
        ),
        migrations.AlterModelTable(
            name='registration',
            table='api_registration',
        ),
    ]
