# Generated by Django 5.2.1 on 2025-05-27 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registration_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
