# Generated by Django 5.2.1 on 2025-05-27 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_registration_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='country_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message="Country code must be in format '+XXX' (e.g., +971)", regex='^\\+\\d{1,4}$')]),
        ),
    ]
